name: schedule
on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"
jobs:
  schedule:
    runs-on: ubuntu-latest
    steps:
      - name: init
        run: |
          echo "${{ github.event.repository.name }}"
          echo
          echo
          env
          echo
          echo
          echo "${{ toJson(github) }}"
